### PR TITLE
Fix issue with reporting the @productboard/relay/unused-fields is unused

### PR DESCRIPTION
**Pull request by vaclavbohac**
Fixes issue with eslint reporting the rule is unused, altough it's reporting errors.

### CODE REVIEW

**Comment by vaclavbohac** [comment]
Current dependencies on/for this PR:
* main
  * **PR #11** <a href="https://app.graphite.dev/github/pr/productboard/eslint-plugin-relay/11" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/productboard/eslint-plugin-relay/11?utm_source=stack-comment).

**Comment by comatory** [comment]
Unfortunately this does not seem to work. What I've tried:

Copy the source to `node_modules/` in FE application. Run `nx lint pm-entity-feature`. I can still see warnings about unused `eslint-disable` for `@productboard/relay/*` rules.

I might've also break some things as it seems like some things were not reported properly.

**Review by comatory — CHANGES_REQUESTED** [review]
Unfortunately this does not seem to work. What I've tried:

Copy the source to `node_modules/` in FE application. Run `nx lint pm-entity-feature`. I can still see warnings about unused `eslint-disable` for `@productboard/relay/*` rules.

I might've also break some things as it seems like some things were not reported properly.

**Comment by vaclavbohac** [comment]
Yep, closing this PR. I will give it one last attempt this week.

**Pull request closed without merging**
